name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: get code
        uses: actions/checkout@v4
               
      - name: Setup Node.js environment
        uses: actions/setup-node@v4    
        with:
          node-version: 18.20.3
      - name: install npm dependencies
        run: npm ci
      - name: npm test
        run: npm test
        
            
            
            
