name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: get code
        uses: actions/checkout@v4.1.6
               
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2    
        with:
          node-version: 18
      - name: install npm dependencies
        run: npm install
      - name: npm test
        run: npm test
        
            
            
            
