name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: get code
        uses: actions/checkout@v4
               
      - name: Setup Node.js environment
        uses: actions/setup-node@v4    
        with:
          node-version: 16
      - name: install npm dependencies
        run: npm ci
        
      - name: upload arctifact
        uses: actions/upload-artifact@v4
        with:
          name: file-uploded
          path: package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy code 
        run: echo "deploying...
      - name: download arctifact
        uses: actions/download-artifact@v4
        with:
          name: file-uploded
      - name: output 
        run: ls

     
    
  
      # - name: npm test
      #   run: npm test
        
            
            
            
