name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: get code
        uses: actions/checkout@v4.1.6
      - name: Set up Node js
        uses: actions/setup-node@v3
        with:
          node-version: '14.14.0'
      - name: install npm dependencies
        run: npm install
      - name: npm test
        run: npm tests 
        
            
            
            
